image: quay.io/podman/stable

stages:
  - build
  - push

docker:build:
  stage: build
  only:
    - master
  before_script:  
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - podman build -t $CI_REGISTRY/$CI_PROJECT_PATH:v2 .
  
docker:push:
  stage: push
  only:
    - master
  before_script:  
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - podman push $CI_REGISTRY/$CI_PROJECT_PATH:v2
