image: docker:dind

stages:
  - build
  - push

docker:build:
  stage: build
  only:
    - master
  before_script:  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:v2 .
  
docker:push:
  stage: push
  only:
    - master
  before_script:  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:v2
