version: '3'
services:
  
  status-api:
    image: registry.git.leon.wtf/leon/status-api:latest
    container_name: status-api
    ports:
      - 3002:3002
    volumes:
      - ./config.json:/config.json:ro
      - ./db.sqlite:/db.sqlite