services:  
  status-api:
    image: registry.git.leon.wtf/leon/status-api:latest
    container_name: status-api
    ports:
      - 3002:3002
    volumes:
      - ./db.sqlite:/db.sqlite
      - ./config.json:/config.json:ro
      # Uncomment next line to provide your own logo
      #- ./logo.png:/logo.png:ro
    environment:
      TZ: Europe/Berlin
